### ISSUE TITLE
Inquiry about Open-Sourcing

### ISSUE THREAD

**Issue by P2Oileen** [cjeen/GenesisTexPaper#1]
I have came across your paper and found it incredibly interesting and valuable! I am reaching out to inquire about the possibility of your work being open-sourced. Should there be any plans for open-sourcing, could you kindly provide an expected timeframe? Anyway thank you for your facinating work😊

**Comment by cjeen** [comment]
@P2Oileen Thank you for your interest. Unfortunately, the algorithm we have proposed is part of a commercial project, so we are unable to open-source it. However, we may be able to provide some results on your dataset (should not be too large due to the cost of computational resources). Additionally, if you plan to reproduce our work, I believe the accuracy of the engineering implementation of rendering and inverse rendering has a significant impact on the results. If you encounter any issues during the reproduction process, please feel free to open an issue and ask for assistance.

**Comment by cjeen** [comment]
@P2Oileen Thank you for your interest. Unfortunately, the algorithm we have proposed is part of a large engineering project, and we do not intend to open source at this moment. However, we may be able to provide some results on your dataset (should not be too large due to the cost of computational resources). Additionally, if you plan to reproduce our work, I believe the accuracy of the engineering implementation of rendering and inverse rendering has a significant impact on the results. If you encounter any issues during the reproduction process, please feel free to open an issue and ask for assistance.
